# Generated by Django 3.0.4 on 2020-03-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=500)),
                ('numeric_column', models.CharField(max_length=500)),
            ],
            options={
                'unique_together': {('table_name', 'numeric_column')},
            },
        ),
    ]
